#! /bin/bash
# make_dirs - makes directories from submitted files
#

EXITCODE=0
DIR="../submissions"

#
# iterate through files, creates directories
# and copies files into the directories
#

for i in $(ls $DIR)
do
    if [ -f "${DIR}/${i}" ]
    then
    DIRNAME=$(echo ${i} | sed 's/\(.*\)_[0-9].*/\1/')
    if [ ! -e "${DIR}/${DIRNAME}" ]
    then    
        mkdir ${DIR}/${DIRNAME}
    fi
    FILE=$(echo ${i} | sed 's/.*[0-9]_\(.*\)\.py/\1/')
    #cp ${DIR}/${i} ${DIR}/${DIRNAME}/$FILE.py 
    FILE=$(echo ${FILE} | sed 's/-//')
    FILE=$(echo ${FILE} | sed 's/[0-9]//')
    #echo $DIRNAME
    #echo $FILE
    mv ${DIR}/${i} ${DIR}/${DIRNAME}/$FILE.py 
    fi
done

exit $EXITCODE
